- name: Install latest basic editors and packages
  ansible.builtin.apt:
    name:
      - vim
      - git
      - unattended-upgrades
      - update-notifier-common
    state: latest

- name: Copy unattended-upgrades config files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades